# permissions for end users to view busyboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: busybox-viewer-role
rules:
- apiGroups:
  - cache.taf122
  resources:
  - busyboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.taf122
  resources:
  - busyboxes/status
  verbs:
  - get
