# permissions for end users to edit busyboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: busybox-editor-role
rules:
- apiGroups:
  - cache.taf122
  resources:
  - busyboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.taf122
  resources:
  - busyboxes/status
  verbs:
  - get
